-- Reset the ingredients table
TRUNCATE TABLE ingredients RESTART IDENTITY CASCADE;

-- Populate ingredients table with a comprehensive list
INSERT INTO ingredients (name, category, default_unit, created_at) VALUES
-- Vegetables
('Tomatoes', 'vegetables', 'pieces', NOW()),
('Onions', 'vegetables', 'pieces', NOW()),
('Potatoes', 'vegetables', 'kg', NOW()),
('Carrots', 'vegetables', 'kg', NOW()),
('Bell Peppers', 'vegetables', 'pieces', NOW()),
('Lettuce', 'vegetables', 'pieces', NOW()),
('Spinach', 'vegetables', 'grams', NOW()),
('Broccoli', 'vegetables', 'pieces', NOW()),
('Cauliflower', 'vegetables', 'pieces', NOW()),
('Cucumber', 'vegetables', 'pieces', NOW()),
('Zucchini', 'vegetables', 'pieces', NOW()),
('Eggplant', 'vegetables', 'pieces', NOW()),
('Garlic', 'vegetables', 'pieces', NOW()),
('Ginger', 'vegetables', 'grams', NOW()),
('Sweet Potatoes', 'vegetables', 'kg', NOW()),

-- Fruits
('Apples', 'fruits', 'pieces', NOW()),
('Bananas', 'fruits', 'pieces', NOW()),
('Oranges', 'fruits', 'pieces', NOW()),
('Lemons', 'fruits', 'pieces', NOW()),
('Limes', 'fruits', 'pieces', NOW()),
('Strawberries', 'fruits', 'grams', NOW()),
('Blueberries', 'fruits', 'grams', NOW()),
('Raspberries', 'fruits', 'grams', NOW()),
('Grapes', 'fruits', 'grams', NOW()),
('Mangoes', 'fruits', 'pieces', NOW()),
('Pineapples', 'fruits', 'pieces', NOW()),
('Watermelon', 'fruits', 'pieces', NOW()),
('Peaches', 'fruits', 'pieces', NOW()),
('Pears', 'fruits', 'pieces', NOW()),
('Plums', 'fruits', 'pieces', NOW()),

-- Grains and Cereals
('Rice', 'grains', 'kg', NOW()),
('Pasta', 'grains', 'grams', NOW()),
('Quinoa', 'grains', 'grams', NOW()),
('Oats', 'grains', 'grams', NOW()),
('Flour', 'grains', 'kg', NOW()),
('Bread Crumbs', 'grains', 'grams', NOW()),
('Cornmeal', 'grains', 'grams', NOW()),
('Couscous', 'grains', 'grams', NOW()),
('Barley', 'grains', 'grams', NOW()),
('Brown Rice', 'grains', 'kg', NOW()),

-- Proteins
('Chicken Breast', 'proteins', 'kg', NOW()),
('Ground Beef', 'proteins', 'kg', NOW()),
('Salmon', 'proteins', 'kg', NOW()),
('Tuna', 'proteins', 'cans', NOW()),
('Eggs', 'proteins', 'pieces', NOW()),
('Tofu', 'proteins', 'grams', NOW()),
('Chickpeas', 'proteins', 'cans', NOW()),
('Black Beans', 'proteins', 'cans', NOW()),
('Lentils', 'proteins', 'grams', NOW()),
('Pork Chops', 'proteins', 'kg', NOW()),

-- Dairy and Alternatives
('Milk', 'dairy', 'liters', NOW()),
('Cheese', 'dairy', 'grams', NOW()),
('Yogurt', 'dairy', 'grams', NOW()),
('Butter', 'dairy', 'grams', NOW()),
('Cream', 'dairy', 'ml', NOW()),
('Almond Milk', 'dairy', 'liters', NOW()),
('Soy Milk', 'dairy', 'liters', NOW()),
('Coconut Milk', 'dairy', 'ml', NOW()),
('Cream Cheese', 'dairy', 'grams', NOW()),
('Sour Cream', 'dairy', 'grams', NOW()),

-- Condiments and Sauces
('Olive Oil', 'condiments', 'ml', NOW()),
('Soy Sauce', 'condiments', 'ml', NOW()),
('Ketchup', 'condiments', 'ml', NOW()),
('Mayonnaise', 'condiments', 'ml', NOW()),
('Mustard', 'condiments', 'ml', NOW()),
('Hot Sauce', 'condiments', 'ml', NOW()),
('Vinegar', 'condiments', 'ml', NOW()),
('Honey', 'condiments', 'ml', NOW()),
('Maple Syrup', 'condiments', 'ml', NOW()),
('BBQ Sauce', 'condiments', 'ml', NOW()),

-- Spices and Herbs
('Black Pepper', 'spices', 'grams', NOW()),
('Salt', 'spices', 'grams', NOW()),
('Cumin', 'spices', 'grams', NOW()),
('Paprika', 'spices', 'grams', NOW()),
('Cinnamon', 'spices', 'grams', NOW()),
('Oregano', 'spices', 'grams', NOW()),
('Basil', 'spices', 'grams', NOW()),
('Thyme', 'spices', 'grams', NOW()),
('Rosemary', 'spices', 'grams', NOW()),
('Curry Powder', 'spices', 'grams', NOW()),

-- Baking
('Sugar', 'baking', 'grams', NOW()),
('Brown Sugar', 'baking', 'grams', NOW()),
('Baking Powder', 'baking', 'grams', NOW()),
('Baking Soda', 'baking', 'grams', NOW()),
('Vanilla Extract', 'baking', 'ml', NOW()),
('Chocolate Chips', 'baking', 'grams', NOW()),
('Cocoa Powder', 'baking', 'grams', NOW()),
('Yeast', 'baking', 'grams', NOW()),
('Powdered Sugar', 'baking', 'grams', NOW()),
('Cornstarch', 'baking', 'grams', NOW()),

-- Snacks
('Potato Chips', 'snacks', 'grams', NOW()),
('Nuts', 'snacks', 'grams', NOW()),
('Popcorn', 'snacks', 'grams', NOW()),
('Crackers', 'snacks', 'grams', NOW()),
('Pretzels', 'snacks', 'grams', NOW()),
('Trail Mix', 'snacks', 'grams', NOW()),
('Dried Fruit', 'snacks', 'grams', NOW()),
('Granola Bars', 'snacks', 'pieces', NOW()),
('Rice Cakes', 'snacks', 'pieces', NOW()),
('Seeds', 'snacks', 'grams', NOW()),

-- Beverages
('Coffee', 'beverages', 'grams', NOW()),
('Tea', 'beverages', 'pieces', NOW()),
('Orange Juice', 'beverages', 'liters', NOW()),
('Apple Juice', 'beverages', 'liters', NOW()),
('Coconut Water', 'beverages', 'liters', NOW()),
('Sparkling Water', 'beverages', 'liters', NOW()),
('Green Tea', 'beverages', 'pieces', NOW()),
('Hot Chocolate', 'beverages', 'grams', NOW()),
('Lemonade', 'beverages', 'liters', NOW()),
('Sports Drinks', 'beverages', 'bottles', NOW()),

-- Canned Goods
('Tomato Sauce', 'canned', 'cans', NOW()),
('Corn', 'canned', 'cans', NOW()),
('Green Beans', 'canned', 'cans', NOW()),
('Soup', 'canned', 'cans', NOW()),
('Diced Tomatoes', 'canned', 'cans', NOW()),
('Pineapple', 'canned', 'cans', NOW()),
('Peaches', 'canned', 'cans', NOW()),
('Sardines', 'canned', 'cans', NOW()),
('Coconut Milk', 'canned', 'cans', NOW()),
('Mushrooms', 'canned', 'cans', NOW());