// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlzgtdnnuzqvzpxexlsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsemd0ZG5udXpxdnpweGV4bHNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NDc0OTksImV4cCI6MjA2NDAyMzQ5OX0.j3S8ZrJ_SJzaNDOwU55ebx6Mb5W3OByNp3nihnSZpPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);